from pathlib import Path

def edit(file, old, new):
    p=Path(file); text=p.read_text(); assert text.count(old)==1,(file,old[:80],text.count(old));p.write_text(text.replace(old,new))

edit('scripts/smoke-art.mjs', "  await page.goto(url,{timeout:30000});await ready();await snap('01-menu');", "  await page.goto('about:blank');\n  await page.goto(url,{timeout:30000});await ready();await page.waitForFunction(()=>Boolean(window.__arbuzReview));await snap('01-menu');")
edit('scripts/smoke-art.mjs', "const snap=async name=>page.screenshot({path:`${output}/${name}.png`});", "const snap=async name=>{console.log('Screenshot: '+name);return page.screenshot({path:`${output}/${name}.png`,timeout:30000});};")
edit('js/main.js', "playerMesh.rotation.set(0, .28, 0);\n      camera.position.set(4.1, player.pos.y + 2.9, 6.8);\n      camera.lookAt(-1.1, player.pos.y + 1.15, 0);", "playerMesh.rotation.set(0, Math.PI - .18, 0);\n      camera.position.set(-3.4, player.pos.y + 2.35, -5.7);\n      camera.lookAt(1.05, player.pos.y + 1.2, 0);")
edit('js/world.js', "|| Math.hypot(x,z)<2.5) continue;", "|| Math.hypot(x,z)<7) continue;")
edit('js/world.js', '  // Fixed first view. The path stays clear; only the arch\'s side columns collide.', "  for (const [x,z] of [[-9,8],[14,9],[-13,22],[7,28]]) {\n    place(tree(index,rng),x,z,rng()*6.28); obstacles.push({x,z,r:.55});\n  }\n  // Fixed first view. The path stays clear; only the arch's side columns collide.")
edit('js/art/characters.js', "  ring(hip,bronze,.79,.026,[0,.015,0]).rotation.x=Math.PI/2;", "  // Worn strap follows the body instead of an equatorial ring.\n  tube(hip,material('bark','#c7b9a0'),[[-.45,.59,.25],[-.23,.35,.62],[.09,0,.66],[.38,-.43,.40]],.045);\n  const shield=leaf(root.userData.joints.elbowL,material('chitin','#c8c997',twoSided),.66,.29,.12);\n  shield.position.set(-.10,-.52,.12); shield.rotation.z=-.16;\n  const emblem=leaf(root.userData.joints.elbowL,bronze,.30,.055,.025); emblem.position.set(-.1,-.33,.25);")
edit('js/art/materials.js', "// Tileable Fourier noise: deterministic, seamless, independent of browser RNG.\nfunction grain(u, v) {\n  return .5 + .12 * Math.sin(u * 6.283 * 3 + Math.cos(v * 6.283 * 2))\n    + .10 * Math.sin(v * 6.283 * 7 + Math.sin(u * 6.283 * 5))\n    + .06 * Math.sin((u * 31 + v * 17) * 6.283)\n    + .035 * Math.sin((u * 83 - v * 67) * 6.283);\n}", "// Periodic value noise avoids directional striping on soil and stone.\nfunction noise(u, v, size) {\n  const x=u*size,y=v*size,ix=Math.floor(x),iy=Math.floor(y);\n  let fx=x-ix,fy=y-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);\n  const sample=(a,b)=>{let h=Math.imul((a%size)+17,374761393)^Math.imul((b%size)+31,668265263);h=Math.imul(h^(h>>>13),1274126177);return ((h^(h>>>16))>>>0)/4294967295;};\n  return mix(mix(sample(ix,iy),sample(ix+1,iy),fx),mix(sample(ix,iy+1),sample(ix+1,iy+1),fx),fy);\n}\nfunction grain(u,v){return noise(u,v,5)*.52+noise(u,v,19)*.30+noise(u,v,73)*.18;}")
edit('js/art/materials.js', "    soil: ['#30382c', '#868260'], leaf:", "    soil: ['#5a5840', '#a3a080'], leaf:")
edit('js/art/materials.js', '    heights[p] = h + speck;', "    heights[p] = h + speck * (kind === 'soil' ? .3 : 1);")
print('Visual review corrections applied')
